AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Lambda Slack Handler

  '
Metadata:
  AWS::ServerlessRepo::Application:
    Name: lambda-slack-handler
    Description: Filters CloudWatch logs and publishes them to Slack
    Author: First and Third
    SpdxLicenseId: MIT
    LicenseUrl: s3://lambda-slack-handler/181bf02877e94d6a352991e44d6ee352
    ReadmeUrl: s3://lambda-slack-handler/c254a1e5070031c54140c8292321144a
    Labels:
    - serverless
    - slack
    - CloudWatch
    - logs
    HomePageUrl: https://github.com/firstandthird/lambda-slack-handler
    SemanticVersion: 1.0.1
    SourceCodeUrl: https://github.com/firstandthird/lambda-slack-handler/tree/1.0.0
Parameters:
  SlackUrl:
    Description: Webhook URL for integration with Slack
    Type: String
  SlackChannel:
    Description: Channel to send message to
    Type: String
  SlackUsername:
    Description: Name to post as
    Type: String
Resources:
  LambdaSlackHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://lambda-slack-handler/7c5aec6fb6fb0a6a2e24adc0c37ae0f4
      Handler: index.handler
      Runtime: nodejs10.x
      Environment:
        Variables:
          SLACK_HOOK:
            Ref: SlackUrl
          SLACK_CHANNEL:
            Ref: SlackChannel
          SLACK_USERNAME:
            Ref: SlackUsername
Outputs:
  LambdaToSlackArn:
    Description: Lambda Slack Function Name ARN
    Value:
      Fn::GetAtt:
      - LambdaSlackHandler
      - Arn
